# Cargo configuration for ricochet-cli

# For private repository authentication in CI
# Option 1: Use git credential helper with token
[net]
git-fetch-with-cli = true

# Option 2: Use direct token replacement (uncomment and set token)
# [url."https://<token>@github.com/"]
# insteadOf = "https://github.com/"
#

[target.x86_64-apple-darwin]
linker = "x86_64-apple-darwin24.5-clang"
ar = "x86_64-apple-darwin24.5-ar"

[target.aarch64-apple-darwin]
linker = "aarch64-apple-darwin24.5-clang"
ar = "aarch64-apple-darwin24.5-ar"
